# Generated by Django 4.2 on 2023-05-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(default=None, upload_to='pics/'),
            preserve_default=False,
        ),
    ]
