# Generated by Django 4.2 on 2023-05-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_cart_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatitems',
            old_name='cimage',
            new_name='bimage',
        ),
        migrations.RenameField(
            model_name='combooffer',
            old_name='cimage',
            new_name='bimage',
        ),
        migrations.RenameField(
            model_name='dailyspecial',
            old_name='dimage',
            new_name='bimage',
        ),
        migrations.RenameField(
            model_name='fastfood',
            old_name='Fimage',
            new_name='bimage',
        ),
        migrations.RenameField(
            model_name='freshjuice',
            old_name='fimage',
            new_name='bimage',
        ),
        migrations.RenameField(
            model_name='lunch',
            old_name='limage',
            new_name='bimage',
        ),
    ]
